export function buildAdminPage() {

  var css = [
    ':root{--bg:#0a0e14;--bg2:#131a24;--bg3:#1a2332;--bg4:#243044;--accent:#00d4ff;--accent2:#0099cc;--green:#00e676;--red:#ff4757;--yellow:#ffbe0b;--purple:#b388ff;--text:#e0e8f0;--text2:#7a8ba0;--text3:#4a5a6a;--radius:12px;--glow:0 0 20px rgba(0,212,255,.15)}',
    '*{box-sizing:border-box;margin:0;padding:0}',
    'body{font-family:"Inter",-apple-system,system-ui,sans-serif;background:var(--bg);color:var(--text);min-height:100vh;overflow-x:hidden}',
    '@import url("https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap");',
    // Header
    '.header{background:linear-gradient(135deg,rgba(19,26,36,.95),rgba(26,35,50,.95));backdrop-filter:blur(20px);border-bottom:1px solid rgba(0,212,255,.15);padding:1rem 2rem;display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:1rem;position:sticky;top:0;z-index:100}',
    '.header h1{font-size:1.5rem;font-weight:700;background:linear-gradient(135deg,#00d4ff,#b388ff);-webkit-background-clip:text;-webkit-text-fill-color:transparent;letter-spacing:-.5px}',
    '.header .info{font-size:.78rem;color:var(--text2);background:rgba(0,212,255,.06);padding:5px 14px;border-radius:20px;border:1px solid rgba(0,212,255,.15);transition:all .3s}',
    // Nav
    '.nav{display:flex;background:var(--bg2);border-bottom:1px solid var(--bg4);overflow-x:auto;scrollbar-width:none}',
    '.nav::-webkit-scrollbar{display:none}',
    '.nav button{background:none;border:none;color:var(--text2);padding:14px 26px;cursor:pointer;font-size:.88rem;font-weight:500;border-bottom:2px solid transparent;white-space:nowrap;transition:all .25s;position:relative}',
    '.nav button:hover{color:var(--text);background:rgba(0,212,255,.04)}',
    '.nav button.active{color:var(--accent);border-bottom-color:var(--accent)}',
    '.nav button.active::after{content:"";position:absolute;bottom:-1px;left:20%;right:20%;height:2px;background:var(--accent);border-radius:2px;box-shadow:0 0 8px var(--accent)}',
    // Layout
    '.container{max-width:960px;margin:0 auto;padding:2rem 1rem}',
    '.page{display:none;animation:fadeIn .3s ease}.page.active{display:block}',
    '@keyframes fadeIn{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}',
    // Login
    '.login-box{max-width:380px;margin:6rem auto;text-align:center;animation:fadeIn .5s ease}',
    '.login-box h2{font-size:2rem;font-weight:700;background:linear-gradient(135deg,#00d4ff,#b388ff);-webkit-background-clip:text;-webkit-text-fill-color:transparent;margin-bottom:.5rem}',
    '.login-box p{color:var(--text2);margin-bottom:2rem;font-size:.9rem}',
    '.login-box .logo{font-size:3rem;margin-bottom:1rem;filter:drop-shadow(0 0 20px rgba(0,212,255,.3))}',
    // Inputs
    'input,textarea{background:rgba(10,14,20,.8);color:var(--text);border:1px solid var(--bg4);padding:13px 16px;border-radius:var(--radius);width:100%;margin-bottom:12px;font-family:"JetBrains Mono",monospace;font-size:.87rem;transition:all .25s}',
    'input:focus,textarea:focus{outline:none;border-color:var(--accent);box-shadow:0 0 0 3px rgba(0,212,255,.1)}',
    'input::placeholder,textarea::placeholder{color:var(--text3)}',
    // Buttons
    '.btn{padding:9px 18px;border-radius:var(--radius);border:none;cursor:pointer;font-size:.84rem;font-weight:600;transition:all .25s;display:inline-flex;align-items:center;gap:6px;margin:3px}',
    '.btn:hover{transform:translateY(-1px);box-shadow:var(--glow)}',
    '.btn:active{transform:scale(.97)}',
    '.btn-primary{background:linear-gradient(135deg,#00e676,#00c853);color:#000}',
    '.btn-blue{background:linear-gradient(135deg,#00d4ff,#0099cc);color:#000}',
    '.btn-secondary{background:var(--bg4);color:var(--text)}',
    '.btn-danger{background:linear-gradient(135deg,#ff4757,#ff2d40);color:#fff}',
    '.btn-warn{background:linear-gradient(135deg,#ffbe0b,#f59e0b);color:#000}',
    '.btn-sm{padding:5px 12px;font-size:.75rem;border-radius:8px}',
    // Cards
    '.card{background:linear-gradient(135deg,rgba(19,26,36,.9),rgba(26,35,50,.7));border:1px solid var(--bg4);border-radius:14px;padding:1.3rem;margin-bottom:14px;backdrop-filter:blur(10px);transition:border-color .3s}',
    '.card:hover{border-color:rgba(0,212,255,.2)}',
    '.stitle{color:var(--text2);font-size:.78rem;text-transform:uppercase;letter-spacing:1.5px;font-weight:600;margin:1.8rem 0 1rem;padding-bottom:.6rem;border-bottom:1px solid var(--bg4)}',
    // Stats
    '.stats-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(160px,1fr));gap:12px;margin-bottom:1.8rem}',
    '.stat-card{background:linear-gradient(135deg,rgba(19,26,36,.95),rgba(26,35,50,.8));border:1px solid var(--bg4);border-radius:14px;padding:1.2rem;text-align:center;transition:all .3s}',
    '.stat-card:hover{border-color:var(--accent);box-shadow:var(--glow);transform:translateY(-2px)}',
    '.stat-card .num{font-size:2rem;font-weight:700;background:linear-gradient(135deg,#00d4ff,#b388ff);-webkit-background-clip:text;-webkit-text-fill-color:transparent}',
    '.stat-card .label{font-size:.7rem;color:var(--text2);margin-top:6px;text-transform:uppercase;letter-spacing:1px}',
    // Table
    'table{width:100%;border-collapse:collapse;font-size:.84rem}',
    'th{text-align:left;padding:12px 14px;color:var(--text3);border-bottom:1px solid var(--bg4);font-size:.7rem;text-transform:uppercase;letter-spacing:.8px;font-weight:600}',
    'td{padding:12px 14px;border-bottom:1px solid rgba(36,48,68,.5);vertical-align:middle}',
    'tr{transition:background .2s}',
    'tr:hover td{background:rgba(0,212,255,.02)}',
    // Badges
    '.badge{display:inline-block;padding:4px 12px;border-radius:20px;font-size:.7rem;font-weight:600}',
    '.badge-green{background:rgba(0,230,118,.1);color:var(--green);border:1px solid rgba(0,230,118,.2)}',
    '.badge-red{background:rgba(255,71,87,.1);color:var(--red);border:1px solid rgba(255,71,87,.2)}',
    '.badge-blue{background:rgba(0,212,255,.1);color:var(--accent);border:1px solid rgba(0,212,255,.2)}',
    '.badge-purple{background:rgba(179,136,255,.1);color:var(--purple);border:1px solid rgba(179,136,255,.2)}',
    // Misc
    '.mono{font-family:"JetBrains Mono",monospace;font-size:.8rem;color:var(--yellow)}',
    '.actions{display:flex;gap:4px;flex-wrap:wrap}',
    '.info-box{background:rgba(10,14,20,.6);border:1px solid var(--bg4);border-radius:var(--radius);padding:12px 16px;font-family:"JetBrains Mono",monospace;font-size:.84rem;color:var(--accent);margin-bottom:10px;word-break:break-all}',
    '.help-text{color:var(--text3);font-size:.82rem;margin-top:8px;line-height:1.7}',
    '.help-text code{background:rgba(0,212,255,.08);padding:2px 8px;border-radius:6px;color:var(--yellow);font-size:.78rem;font-family:"JetBrains Mono",monospace}',
    '.row{display:flex;gap:8px;flex-wrap:wrap;margin:8px 0}',
    '.toast{position:fixed;bottom:24px;right:24px;padding:14px 28px;border-radius:var(--radius);color:#fff;font-weight:600;z-index:9999;display:none;box-shadow:0 8px 32px rgba(0,0,0,.4);backdrop-filter:blur(10px);font-size:.88rem}',
    '.twrap{overflow-x:auto}',
    '.glow-border{box-shadow:var(--glow)}',
    '@media(max-width:768px){.stats-grid{grid-template-columns:repeat(2,1fr)}.container{padding:1rem .5rem}}',
  ].join('');

  var body = [
    '<div class="header"><h1>&#9889; DeepSeek2API</h1><span class="info" id="hInfo">Not logged in</span></div>',
    '<div class="nav" id="navBar">',
    '<button onclick="sp(\'login\')" id="nav-login" class="active">Login</button>',
    '</div>',
    '<div class="container">',

    // Login
    '<div class="page active" id="page-login"><div class="login-box">',
    '<div class="logo">&#128171;</div>',
    '<h2>DeepSeek2API</h2><p>Reverse Proxy Admin Panel</p>',
    '<input type="password" id="pwdInput" placeholder="Admin password">',
    '<button class="btn btn-blue" onclick="doLogin()" style="width:100%;padding:14px;font-size:1rem;justify-content:center">&#128274; Authenticate</button>',
    '<div id="loginErr" style="color:var(--red);font-size:.85rem;margin-top:10px;min-height:18px"></div>',
    '</div></div>',

    // Dashboard
    '<div class="page" id="page-dashboard">',
    '<div class="stitle">Overview</div>',
    '<div class="stats-grid" id="statsGrid"></div>',
    '<div class="card">',
    '<div class="stitle" style="margin-top:0">Connection Info</div>',
    '<div class="info-box" id="infoBase"></div>',
    '<div class="info-box">GET /v1/models</div>',
    '<div class="info-box">POST /v1/chat/completions</div>',
    '</div>',
    '<div class="card">',
    '<div class="stitle" style="margin-top:0">Notes</div>',
    '<p class="help-text">DeepSeek PoW challenges are solved automatically via embedded WASM.<br><br>',
    'Model variants: <code>deepseek-v4-pro</code> (expert), <code>deepseek-v4-flash</code> (instant).<br>Append <code>-thinking</code> or <code>-search</code> for features.<br><br>',
    'Accounts use email/password login. Tokens auto-refresh on each request.</p>',
    '</div></div>',

    // Accounts
    '<div class="page" id="page-accounts">',
    '<div class="stitle">Add Account</div>',
    '<div class="card">',
    '<input type="email" id="accEmail" placeholder="DeepSeek Email (Required)">',
    '<button class="btn btn-blue" onclick="launchAutomatedBrowser()" style="width:100%; justify-content:center; padding:12px; margin-bottom:10px;">&#127760; Launch Live Browser (VNC) to Login</button>',
    '<p class="help-text">Click the button above to open a live virtual browser on the server. You can solve Captchas manually, and the proxy will steal the <code>ds_session_id</code> natively!</p>',
    '<div id="vncContainer" style="display:none; margin-top:15px; border:1px solid rgba(0,212,255,0.4); border-radius:8px; overflow:hidden;"></div>',
    '<hr style="border:0; border-bottom:1px solid rgba(255,255,255,0.1); margin:18px 0;">',
    '<p class="help-text" style="color:var(--text3); font-size:0.75rem; margin-bottom:6px">Or use legacy cURL extraction manually:</p>',
    '<textarea id="accToken" rows="2" placeholder="Paste cURL dump here..." style="resize:vertical"></textarea>',
    '<button class="btn btn-secondary btn-sm" onclick="addAccountToken()">Extract Session from cURL</button>',
    '</div>',
    '<div class="stitle">Account List</div>',
    '<div class="card"><div class="twrap"><table>',
    '<thead><tr><th>Email</th><th>Status</th><th>Token</th><th>Requests</th><th>Last Used</th><th>Actions</th></tr></thead>',
    '<tbody id="accTbl"></tbody>',
    '</table></div></div></div>',

    // API Keys
    '<div class="page" id="page-keys">',
    '<div class="stitle">Generate Key</div>',
    '<div class="card"><div class="row">',
    '<input type="text" id="keyName" placeholder="Key name (e.g. SillyTavern)" style="flex:1">',
    '<button class="btn btn-blue" onclick="createKey()">&#128273; Generate</button>',
    '</div></div>',
    '<div class="stitle">Key List</div>',
    '<div class="card"><div class="twrap"><table>',
    '<thead><tr><th>Name</th><th>Key</th><th>Status</th><th>Requests</th><th>Created</th><th>Actions</th></tr></thead>',
    '<tbody id="keyTbl"></tbody>',
    '</table></div></div></div>',

    // Models
    '<div class="page" id="page-models">',
    '<div class="stitle">Add Model</div>',
    '<div class="card"><div class="row">',
    '<input type="text" id="mdlId" placeholder="Model ID (e.g. deepseek_chat)" style="flex:1">',
    '<input type="text" id="mdlName" placeholder="Display name (optional)" style="flex:1">',
    '<button class="btn btn-primary" onclick="addModel()">Add</button>',
    '</div></div>',
    '<div class="stitle">Model List</div>',
    '<div class="card"><div class="twrap"><table>',
    '<thead><tr><th>Model ID</th><th>Display Name</th><th>Status</th><th>Actions</th></tr></thead>',
    '<tbody id="mdlTbl"></tbody>',
    '</table></div></div></div>',

    // Sessions
    '<div class="page" id="page-sessions">',
    '<div class="stitle" style="display:flex;justify-content:space-between;align-items:center">',
    '<span>Active Sessions</span>',
    '<button class="btn btn-warn btn-sm" onclick="clearConvs()">Clear All</button>',
    '</div>',
    '<div class="card"><div class="twrap"><table>',
    '<thead><tr><th>Session</th><th>Account</th><th>Model</th><th>Msgs</th><th>Last Active</th></tr></thead>',
    '<tbody id="sessTbl"></tbody>',
    '</table></div></div></div>',

    '</div>',
    '<div class="toast" id="toast"></div>',
  ].join('');

  var js = [
    'var token=localStorage.getItem("ds2a_token")||"";',
    'var loggedIn=false;',
    '',
    'function sp(n){',
    '  if(["dashboard","accounts","keys","models","sessions"].indexOf(n)!==-1&&!loggedIn){sp("login");toast("Login first","#ff4757");return;}',
    '  var ps=document.querySelectorAll(".page"),bs=document.querySelectorAll(".nav button");',
    '  for(var i=0;i<ps.length;i++)ps[i].classList.remove("active");',
    '  for(var i=0;i<bs.length;i++)bs[i].classList.remove("active");',
    '  var p=document.getElementById("page-"+n),b=document.getElementById("nav-"+n);',
    '  if(p)p.classList.add("active");if(b)b.classList.add("active");',
    '  if(n==="dashboard")loadDash();',
    '  if(n==="accounts")loadAccounts();',
    '  if(n==="keys")loadKeys();',
    '  if(n==="models")loadModels();',
    '  if(n==="sessions")loadSessions();',
    '}',
    '',
    'function hdr(){return{"Authorization":"Bearer "+token,"Content-Type":"application/json"};}',
    '',
    'function api(path,opts){',
    '  opts=opts||{};opts.headers=hdr();',
    '  return fetch(path,opts).then(function(r){return r.json().then(function(d){if(!r.ok)throw new Error(d.error||"Request failed");return d;});});',
    '}',
    '',
    'function toast(m,c){var t=document.getElementById("toast");t.textContent=m;t.style.background=c||"#00e676";t.style.display="block";setTimeout(function(){t.style.display="none";},3000);}',
    'function esc(s){var d=document.createElement("div");d.textContent=s;return d.innerHTML;}',
    'function maskKey(k){return k.slice(0,14)+"\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022"+k.slice(-4);}',
    'function timeAgo(d){if(!d)return"\\u2014";var s=Math.floor((Date.now()-new Date(d+"Z").getTime())/1000);if(s<60)return s+"s ago";if(s<3600)return Math.floor(s/60)+"m ago";if(s<86400)return Math.floor(s/3600)+"h ago";return Math.floor(s/86400)+"d ago";}',
    'function cp(text){navigator.clipboard.writeText(text).then(function(){toast("Copied!","#00e676");}).catch(function(){toast("Copy failed","#ff4757");});}',
    '',
    '// ── Auth ──',
    'function doLogin(){',
    '  var pw=document.getElementById("pwdInput").value;',
    '  if(!pw){toast("Enter password","#ff4757");return;}',
    '  fetch("/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:pw})})',
    '  .then(function(r){return r.json().then(function(d){if(!r.ok)throw new Error(d.error);return d;});})',
    '  .then(function(d){',
    '    token=d.token;loggedIn=true;localStorage.setItem("ds2a_token",token);',
    '    document.getElementById("hInfo").textContent="Admin \\u2714";',
    '    document.getElementById("hInfo").style.borderColor="#00e676";',
    '    buildNav();sp("dashboard");toast("Authenticated!","#00e676");',
    '  }).catch(function(e){document.getElementById("loginErr").textContent=e.message;token="";localStorage.removeItem("ds2a_token");});',
    '}',
    '',
    'function logout(){token="";loggedIn=false;localStorage.removeItem("ds2a_token");location.reload();}',
    '',
    'function buildNav(){',
    '  var nav=document.getElementById("navBar");nav.innerHTML="";',
    '  var tabs=[["dashboard","Dashboard"],["accounts","Accounts"],["keys","API Keys"],["models","Models"],["sessions","Sessions"]];',
    '  for(var i=0;i<tabs.length;i++){var btn=document.createElement("button");btn.id="nav-"+tabs[i][0];btn.textContent=tabs[i][1];btn.setAttribute("data-p",tabs[i][0]);btn.onclick=function(){sp(this.getAttribute("data-p"));};nav.appendChild(btn);}',
    '  var lbtn=document.createElement("button");lbtn.textContent="Logout";lbtn.onclick=logout;nav.appendChild(lbtn);',
    '}',
    '',
    'document.getElementById("pwdInput").addEventListener("keydown",function(e){if(e.key==="Enter")doLogin();});',
    '',
    '// ── Dashboard ──',
    'function loadDash(){',
    '  document.getElementById("infoBase").textContent=location.origin+"/v1";',
    '  var sg=document.getElementById("statsGrid");',
    '  Promise.all([api("/admin/accounts").catch(function(){return[];}),api("/admin/keys").catch(function(){return[];}),api("/admin/models").catch(function(){return[];}),api("/admin/conversations").catch(function(){return[];})]).then(function(res){',
    '    var accs=res[0]||[];var keys=res[1]||[];var mdls=res[2]||[];var convs=res[3]||[];',
    '    var activeAccs=accs.filter(function(r){return r.active;}).length;',
    '    var activeKeys=keys.filter(function(r){return r.active;}).length;',
    '    var totalReqs=accs.reduce(function(s,r){return s+(r.request_count||0);},0);',
    '    sg.innerHTML=sc(activeAccs,"Accounts")+sc(activeKeys,"API Keys")+sc(mdls.length,"Models")+sc(totalReqs,"Requests")+sc(convs.length,"Sessions");',
    '  });',
    '}',
    'function sc(v,l){return "<div class=\\"stat-card\\"><div class=\\"num\\">"+v+"</div><div class=\\"label\\">"+l+"</div></div>";}',
    '',
    '// ── Accounts ──',
    'function loadAccounts(){',
    '  api("/admin/accounts").then(function(rows){',
    '    var tb=document.getElementById("accTbl");',
    '    if(!rows.length){tb.innerHTML="<tr><td colspan=\\"6\\" style=\\"text-align:center;color:var(--text3);padding:24px\\">No accounts yet.</td></tr>";return;}',
    '    var h="";for(var i=0;i<rows.length;i++){var r=rows[i];',
    '      h+="<tr><td class=\\"mono\\">"+esc(r.email)+"</td>";',
    '      h+="<td><span class=\\"badge "+(r.active?"badge-green":"badge-red")+"\\">"+(r.active?"Active":"Off")+"</span></td>";',
    '      h+="<td><span class=\\"badge "+(r.token?"badge-purple":"badge-red")+"\\">"+(r.token?"Has Token":"No Token")+"</span></td>";',
    '      h+="<td>"+r.request_count+"</td>";',
    '      h+="<td style=\\"color:var(--text2)\\">"+timeAgo(r.last_used)+"</td>";',
    '      h+="<td class=\\"actions\\">";',
    '      h+="<button class=\\"btn btn-secondary btn-sm\\" onclick=\\"togAcc("+r.id+","+(r.active?0:1)+")\\">"+(r.active?"Disable":"Enable")+"</button>";',
    '      h+="<button class=\\"btn btn-danger btn-sm\\" onclick=\\"delAcc("+r.id+")\\">Del</button>";',
    '      h+="</td></tr>";',
    '    }tb.innerHTML=h;',
    '  }).catch(function(e){toast(e.message,"#ff4757");});',
    '}',
    '',
    'function launchAutomatedBrowser(){',
    '  var email=document.getElementById("accEmail").value.trim();',
    '  if(!email){toast("Enter DeepSeek email first","#ff4757");return;}',
    '  api("/admin/browser/launch",{method:"POST",body:JSON.stringify({email:email})})',
    '  .then(function(){',
    '    toast("Browser starting!","#00e676");',
    '    var vc=document.getElementById("vncContainer");',
    '    vc.style.display="block";',
    '    vc.innerHTML=\'<div style="padding:40px;text-align:center;color:var(--text2);">Booting VNC Server (Please wait 4s)...</div>\';',
    '    setTimeout(function() {',
    '      vc.innerHTML=\\\'<iframe src="/novnc/vnc_lite.html?autoconnect=true&resize=remote&reconnect=true" style="width:100%;height:600px;border:none;"></iframe>\\\';',
    '    }, 4000);',
    '    setInterval(loadAccounts, 3000);',
    '  })',
    '  .catch(function(e){toast(e.message,"#ff4757");});',
    '}',
    '',
    'function addAccountToken(){',
    '  var email=document.getElementById("accEmail").value.trim();',
    '  var token=document.getElementById("accToken").value.trim();',
    '  if(!email||!token){toast("Email label and cURL token required","#ff4757");return;}',
    '  api("/admin/accounts",{method:"POST",body:JSON.stringify({email:email,token:token})})',
    '  .then(function(d){document.getElementById("accEmail").value="";document.getElementById("accToken").value="";toast(d.message||"Extracted & Added!","#00e676");loadAccounts();})',
    '  .catch(function(e){toast(e.message,"#ff4757");});',
    '}',
    '',
    'function togAcc(id,active){api("/admin/accounts/"+id,{method:"PATCH",body:JSON.stringify({active:!!active})}).then(function(){loadAccounts();});}',
    'function delAcc(id){if(!confirm("Delete this account?"))return;api("/admin/accounts/"+id,{method:"DELETE"}).then(function(){toast("Deleted","#00e676");loadAccounts();});}',
    '',
    '// ── API Keys ──',
    'function loadKeys(){',
    '  api("/admin/keys").then(function(rows){',
    '    var tb=document.getElementById("keyTbl");',
    '    if(!rows.length){tb.innerHTML="<tr><td colspan=\\"6\\" style=\\"text-align:center;color:var(--text3);padding:24px\\">No keys yet.</td></tr>";return;}',
    '    var h="";for(var i=0;i<rows.length;i++){var r=rows[i];',
    '      h+="<tr><td>"+esc(r.name||"\\u2014")+"</td>";',
    '      h+="<td class=\\"mono\\" style=\\"cursor:pointer\\" onclick=\\"cp(\'"+esc(r.key)+"\')\\" >"+maskKey(r.key)+"</td>";',
    '      h+="<td><span class=\\"badge "+(r.active?"badge-green":"badge-red")+"\\">"+(r.active?"Active":"Off")+"</span></td>";',
    '      h+="<td>"+r.request_count+"</td>";',
    '      h+="<td style=\\"color:var(--text2)\\">"+timeAgo(r.created_at)+"</td>";',
    '      h+="<td class=\\"actions\\">";',
    '      h+="<button class=\\"btn btn-secondary btn-sm\\" onclick=\\"togKey("+r.id+","+(r.active?0:1)+")\\">"+(r.active?"Disable":"Enable")+"</button>";',
    '      h+="<button class=\\"btn btn-danger btn-sm\\" onclick=\\"delKey("+r.id+")\\">Del</button>";',
    '      h+="</td></tr>";',
    '    }tb.innerHTML=h;',
    '  }).catch(function(e){toast(e.message,"#ff4757");});',
    '}',
    '',
    'function createKey(){',
    '  var name=document.getElementById("keyName").value;',
    '  api("/admin/keys",{method:"POST",body:JSON.stringify({name:name})})',
    '  .then(function(d){document.getElementById("keyName").value="";cp(d.key);toast("Key created & copied!","#00e676");loadKeys();})',
    '  .catch(function(e){toast(e.message,"#ff4757");});',
    '}',
    '',
    'function togKey(id,active){api("/admin/keys/"+id,{method:"PATCH",body:JSON.stringify({active:!!active})}).then(function(){loadKeys();});}',
    'function delKey(id){if(!confirm("Delete this key?"))return;api("/admin/keys/"+id,{method:"DELETE"}).then(function(){toast("Deleted","#00e676");loadKeys();});}',
    '',
    '// ── Models ──',
    'function loadModels(){',
    '  api("/admin/models").then(function(rows){',
    '    var tb=document.getElementById("mdlTbl");',
    '    if(!rows.length){tb.innerHTML="<tr><td colspan=\\"4\\" style=\\"text-align:center;color:var(--text3);padding:24px\\">No models.</td></tr>";return;}',
    '    var h="";for(var i=0;i<rows.length;i++){var r=rows[i];',
    '      h+="<tr><td class=\\"mono\\">"+esc(r.model_id)+"</td>";',
    '      h+="<td>"+esc(r.display_name||r.model_id)+"</td>";',
    '      h+="<td><span class=\\"badge "+(r.active?"badge-green":"badge-red")+"\\">"+(r.active?"Listed":"Unlisted")+"</span></td>";',
    '      h+="<td class=\\"actions\\">";',
    '      h+="<button class=\\"btn btn-secondary btn-sm\\" onclick=\\"togMdl("+r.id+","+(r.active?0:1)+")\\">"+(r.active?"Unlist":"List")+"</button>";',
    '      h+="<button class=\\"btn btn-danger btn-sm\\" onclick=\\"delMdl("+r.id+")\\">Del</button>";',
    '      h+="</td></tr>";',
    '    }tb.innerHTML=h;',
    '  }).catch(function(e){toast(e.message,"#ff4757");});',
    '}',
    '',
    'function addModel(){',
    '  var mid=document.getElementById("mdlId").value.trim();var mname=document.getElementById("mdlName").value.trim();',
    '  if(!mid){toast("Model ID required","#ff4757");return;}',
    '  api("/admin/models",{method:"POST",body:JSON.stringify({model_id:mid,display_name:mname})})',
    '  .then(function(){document.getElementById("mdlId").value="";document.getElementById("mdlName").value="";toast("Model added!","#00e676");loadModels();})',
    '  .catch(function(e){toast(e.message,"#ff4757");});',
    '}',
    '',
    'function togMdl(id,active){api("/admin/models/"+id,{method:"PATCH",body:JSON.stringify({active:!!active})}).then(function(){loadModels();});}',
    'function delMdl(id){if(!confirm("Remove this model?"))return;api("/admin/models/"+id,{method:"DELETE"}).then(function(){toast("Deleted","#00e676");loadModels();});}',
    '',
    '// ── Sessions ──',
    'function loadSessions(){',
    '  api("/admin/conversations").then(function(rows){',
    '    var tb=document.getElementById("sessTbl");',
    '    if(!rows.length){tb.innerHTML="<tr><td colspan=\\"5\\" style=\\"text-align:center;color:var(--text3);padding:24px\\">No active sessions.</td></tr>";return;}',
    '    var h="";for(var i=0;i<rows.length;i++){var r=rows[i];',
    '      h+="<tr><td class=\\"mono\\" title=\\""+esc(r.conv_key)+"\\">"+esc((r.conv_key||"").slice(0,16))+"\\u2026</td>";',
    '      h+="<td>"+esc(r.email||"?")+"</td>";',
    '      h+="<td><span class=\\"badge badge-blue\\">"+esc(r.model||"?")+"</span></td>";',
    '      h+="<td>"+r.message_count+"</td>";',
    '      h+="<td style=\\"color:var(--text2)\\">"+timeAgo(r.last_used)+"</td>";',
    '      h+="</tr>";',
    '    }tb.innerHTML=h;',
    '  }).catch(function(){});',
    '}',
    '',
    'function clearConvs(){',
    '  if(!confirm("Clear all sessions?"))return;',
    '  api("/admin/conversations",{method:"DELETE"}).then(function(){toast("Cleared","#00e676");loadSessions();}).catch(function(e){toast(e.message,"#ff4757");});',
    '}',
    '',
    '// ── Auto-login ──',
    'function tryAutoLogin(){',
    '  if(!token)return;',
    '  api("/admin/accounts").then(function(){',
    '    loggedIn=true;document.getElementById("hInfo").textContent="Admin \\u2714";',
    '    document.getElementById("hInfo").style.borderColor="#00e676";buildNav();sp("dashboard");',
    '  }).catch(function(){token="";localStorage.removeItem("ds2a_token");});',
    '}',
    'if(token)tryAutoLogin();',
  ].join('\n');

  return `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>DeepSeek2API</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet"><style>${css}</style></head><body>${body}<script>${js}<\/script></body></html>`;
}
